### ISSUE TITLE
New functin proposal

### ISSUE THREAD

**Issue by RE-A** [shieldnet/CauCrawler#3]
![캡처](https://user-images.githubusercontent.com/11948404/54760706-f345ed00-4c33-11e9-9515-8bd5db9d08ea.PNG)
 위와 같이 이클래스에 새 글이 올라올 경우, 직접 이클래스에 들어가지 않는 이상 새 글이 올라오는 걸 알 수 없습니다. TO Do에 새 글이 올라올 경우 알림을 보내주는 기능을 추가하면 상당히 도움될 것 같습니다. 

To do 영역에서는 저게 어느과목 알림인지 모른다는 문제점이 있어서, 대시보드 자체에서 알림표시 뜬 게 있으면 그걸 크롤링하는 방법도 있겠지만 그건 구현상 힘들거 같아서 그냥 새로운 알림이 떴다는 사실만 알려줘도 큰 도움이 될 것 같습니다.

 개인별로 포탈 아이디와 비밀번호를 입력해서 자동 로그인 하는 식으로(아즈인포에서 했던 방식처럼) 구현할 수 있을까요?..

& 저도 이 프로젝트에 흥미가 있어서 괜찮다면 지원하고 싶습니다! 도움은 별로 안되겠지만..

**Comment by shieldnet** [comment]
Celenium Based Server에서는 Id/pw입력 후 정보 긁어오기가 가능한데, 제가 지금 돌리고 있는 Crawler은 GUI Interface가 없는 AWS Server에서 돌아가고 있기 때문에, headless browser을 이용한 크롤링/자동테스트가 불가능합니다. (Ubuntu LTS 18.04)
